"""added tags to Post table

Revision ID: 0666955b9595
Revises: c0c729f9a155
Create Date: 2020-07-16 22:43:34.311727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0666955b9595'
down_revision = 'c0c729f9a155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tags', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tags')
    # ### end Alembic commands ###
